apiVersion: v1
data:
  elastic_entry: elasticsearch-cluster
  redis_master: master
  redis_slave: slave
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: gd-config
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gd-test-lb
            port:
              number: 80
      - path: /kibana
        pathType: Prefix
        backend:
          service:
            name: kibana-svc
            port:
              number: 5601