apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: LoadBalancer
  ports:
  - name: "5601"
    port: 5601
    targetPort: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  app: kibana
 name: kibana
spec:
 replicas: 1
 selector:
  matchLabels:
   app: kibana
 template:
  metadata:
   labels:
    app: kibana
  spec:
   containers:
   - name: kibana
     env:
     - name: HOST
       valueFrom:
         configMapKeyRef:
           name: gd-config
           key: elastic_entry
     - name: ELASTICSEARCH_HOSTS
       value: "http://$(HOST):9200"
     image: docker.elastic.co/kibana/kibana:7.1.1
     ports:
     - containerPort: 5601
