apiVersion: v1
kind: Service
metadata:
  name: gd-test-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8085
  selector:
    app: gd-test
---
apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: gd-test
  labels:
    app: gd-test                                # 2
spec:                                                # 3
  containers:
    - image: quay.io/myafk/interactive:stable # 4
      name: gd-test                              # 5
      ports:
        - containerPort: 8085                          # 6
      command: ["interactive", "ingress"]
      env:
      - name: ELASTICSEARCH_HOSTS
        value: http://es-node-0:9200
      - name: KUBERNETES_SERVICE_HOST
        value: any string here
      - name: KUBERNETES_SERVICE_PORT
        value: any thing here
      - name: REDIS_MASTER_HOST
        value: master.default.svc.cluster.local
      - name: REDIS_SLAVE_HOST
        value: slave.default.svc.cluster.local
